my_security:
    resource: "@MySecurityBundle/Resources/config/routing.yml"
    prefix:   /


article_form:
    resource: "@ArticleFormBundle/Resources/config/routing.yml"
    prefix:   /


form:
    resource: "@PizzaFormBundle/Resources/config/routing.yml"
    prefix:   /
