my_security_homepage:
    path:     /admin
    defaults: { _controller: MySecurityBundle:Security:admin }
    
usuario_login:
    path: /usuarios/login
    defaults: { _controller: MySecurityBundle:Security:login }
    
usuario_login_check:
    path: /usuarios/login_check
    
usuario_logout:
    path: /usuarios/logout
    
usuarios:
    path: /usuarios
    defaults: { _controller: MySecurityBundle:Security:zonaLogin }
    
people_login:
    path: /people/login
    defaults: { _controller: MySecurityBundle:Security:peopleLogin }
    
people_login_check:
    path: /people/login_check
    
people_logout:
    path: /people/logout
    
people:
    path: /people
    defaults: { _controller: MySecurityBundle:Security:zonaPeople }


people_comments:
    path: /people/comments
    defaults: { _controller: MySecurityBundle:Security:comments }
    
    
people_comment:
    path: /people/comment/{id}
    defaults: { _controller: MySecurityBundle:Security:comment }